#!/bin/bash

if [ $# -ne 1 ]; then
    echo $0: usage: logevent text
    exit 1
fi

text=$1

ts=$(date +%s%N)

curl -i -XPOST 'http://localhost:8086/write?db=crt' --data-binary 'events text="'$1'",title="Run" '$ts''
